/**
 * ASSET DE ÁUDIO: Julia Gamer
 * Formato: Base64 String (Raw PCM 16-bit / 24kHz)
 * Este arquivo permite que o depoimento funcione sem depender de arquivos .mp3 externos.
 */

// Placeholder de áudio silencioso/curto para evitar erro de inicialização
export const JULIA_AUDIO_BASE64 = "AAAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQA=";
